README.md

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

updating deploy button

---

docker/docker-compose.yml

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

mod docker compose envfile path

---

.env.sample
README.md

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

update folder paths in READme

---

docs/web-apps.md

* Fix admin site image url in docs
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fix admin site image url in docs

---

README.md

This introduces changes to reflect rebranding from Cognitive Search to AI Search.
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```

Rebranding from Cognitive Search to AI Search.

---

code/admin/pages/01_Ingest_Data.py
code/utilities/tests/test_Orchestrator.py
infrastructure/deployment.bicep
infrastructure/deployment.json

Rename the product to keep up with Ignite 2023
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Product rebrand after Ignite - now called `Azure AI Search`

---

README.md

* Fix frontend path in docs
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
cd code
cd app
cd frontend
npm install
```
```
```
* ...

Fix frontend path in docs

---

README.md

- Multiple people (myself included) have run into this issue by accidentally deploying the wrong model version
- This PR aims to make it clearer eariler on which version is required
- Also adds a troubleshooting section to help improve self diagnosis
- Happy to take feedback on layout/ordering etc
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Improve docs around which model version is required

---

README.md
infrastructure/deployment.bicep
infrastructure/deployment.json

* ...
This Pull Request to the infrastructure/deployment.json and infrastructure/deployment.bicep files add a new Log Analytics workspace for App Insights as classic deployment is not available in all regions. It also adds a new parameter for the workspace name and updates the Bicep generator version. Additionally, it adds a parameter for the location of the Azure Form Recognizer [Document Intelligence] resource as it is not available in all regions Canada East for example] and updates the storage account name to ensure uniqueness.
Main changes:
* `infrastructure/deployment.json`: Added a new Log Analytics workspace and updates the deployment template to reference it. Added a new parameter for the workspace name and updates the Bicep generator version. Added a parameter for the location …

Update Bicep and ARM Template file to support other Regions for Document Intelligence deployment

---

infrastructure/deployment.bicep

* This change fixes the deployment by changing the default value for param StorageAccountName. 
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
*  Deploy the deployment.bicep file. 
* Deployment should not fail on the value of param StorageAccountName.
This PR addresses issue #89

Fix deployment by changing StorageAccountName.

---

code/batch/BatchPushResults.py

* ...
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

fix: lower function syntax

---

docs/TEAMS_EXTENSION.md

* The "Deploy to Azure" for Teams URL is incorrect. Selecting the button does generate the ARM template. This update fixes the URL.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
N/A
```
```
1. Navigate to the Teams Deployment MD file: https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/TEAMS_EXTENSION.md.
2. Select Deploy to Azure.
```
*

Corrected typo in Teams One Click deployment URL.

---

.github/workflows/dependabot.yaml

- To pickup the new `requirements.txt` file in the `/extensions/backup/` dir
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```

Update dependabot pip directory

---

.devcontainer/devcontainer.json

Add the GitHub Pull Request extension so that it makes it easier to checkout forks into your devcontainer and check the validity of the PR.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
Open in a devcontainer and see if the GitHub PR extension is installed
```

Add GitHub PR extension

---

README.md
infrastructure/deployment.bicep
infrastructure/deployment.json

- Removes a manual pre-req
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
1. Deploy using bicep file/deployment json
```
* The app functions as expected
Fixes https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/108

Create OpenAI resource automatically

---

.github/dependabot.yml

This PR will allow dependabot to find all `requirements.txt` files in the repo:
- `/code/requirements.txt`
- `/code/app/requirements.txt`
- `/extensions/backend/requirements.txt`
Note that if there is a dependency that is common across all three files, there will be two separate PRs for the same update: One for `/code` and one for `/extensions`. They should be tested and upgraded at the same time otherwise the Dev Container post install script will fail due to a mismatch of versions.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: CI/CD/dependencies update
```
Run …

Update dependabot to include all requirements.txt files

---

code/app/app.py

Closes #42 
* Removes `text/event-stream` mimetype from streamed HTTP responses. The response now displays correctly in the browser. the `Content-Type` header now defaults to `text/html; charset=utf-8`.
* Fixes bugs in `/api/conversation/azure_byod` endpoint when making API request to Azure OpenAI
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
* Run API locally
* Make API request from Postman:
* Observe the response
(Compare with before)

Remove mimetype from `/api/conversation/azure_byod` endpoint

---

code/batch/local.settings.json.sample
docs/LOCAL_DEPLOYMENT.md

* Updating the Local_Deployment.md file for debugging functions locally.
```
[ ] Yes
[x] No
```
Updating the local deployment instructions
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

updating docs for local functions debugging

---

code/app/requirements.txt
code/requirements.txt
extensions/backend/requirements.txt

Dependabot update
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
Dependabot
```
Run `code/utilities/tests/test_DocumentProcessor.py`

python-docx 1.1.0 Update

---

code/app/app.py

Closes #42 (again)
Update mimetype to `application/json-lines`. Response now appears correctly in browser/Postman.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
* Hit `/api/conversation/azure_byod` endpoint
See response

Update mimetype for streamed responses to application/json-lines

---

docs/LOCAL_DEPLOYMENT.md

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Add devcontainer docs

---

README.md
docs/TEAMS_EXTENSION.md
extensions/infrastructure/main.bicep
extensions/infrastructure/main.json

Few tweaks to the Teams Extension installation guidance
1. In the pre-reqs define that you need a subscription first as its the first thing you need.
2. Update that you need to be `Owner` not contributor as we now use RBAC
3. Renamed some variables that still mention "Cognitive"
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Teams extension docs guidance

---

infra/deployment.bicep
infra/deployment.json

* Fixes rbac deployment
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

adding auth type config to azure function

---

infra/deployment.bicep
infra/deployment.json

Closes #93 
* Enforce minimum TLS version 1.2.
```
[x] Yes
[] No
```
```
[ ] Bugfix
[x] Feature
```
*  Deploy to Azure
* Check minimum TLS version

Set minimum TLS version to 1.2

---

code/requirements.txt
extensions/backend/requirements.txt

The CI build fails for dependabot as there are separate pr's for the multiple places this is defined
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Bump version of transformers dependency

---

code/requirements.txt

- update azure-search-documents==11.4.0b8
```
[x] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Update requirements.txt azure-search-documents==11.4.0b8

---

README.md

- Remove incorrect statement about prompt flow. If you want customisations, that is a good tool to use.
- I've not added any additional information as I believe the table below explains clearly enough when to use each tool
Required by https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/142
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Remove incorrect statement on when to use prompt flow

---

.github/dependabot.yml
README.md

- Add note about Resource Group location (Fixes #138)
- Specific directories for npm dependabot
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
Can only test this when we get to main as dependabot runs weekly.

Add note if you chose wrong region

---

extensions/teams/infra/azure.bicep
extensions/teams/infra/azure.parameters.json

@ross-p-smith Fixes problem described in issue: https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/379

#379 Add AZURE_FUNCTION_URL as appSetting parameter

---

code/backend/batch/BatchStartProcessing.py
code/backend/batch/GetConversationResponse.py

Fixed import error related to EnvHelper because it was causing a typeError which prevents that func from starting successfully
* ...
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
```
```
cd code/backend/batch
func start --verbose
```
```
func starts without Any TypeError related to EnvHelper class
```

Fixed import error related to EnvHelper in /code/backend/batch/ #387

---

code/backend/pages/01_Ingest_Data.py

The logic behind retrieving the `AZURE_BLOB_ACCOUNT_KEY` should have been encapsulated behind the EnvHelper. EnvHelper does not expose the KeyVault, but rather exposes the values/secrets based on Feature Flags.
Fixes #387
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
- Go to Admin Page
- Upload a file

Fix ingestion of documents in Admin app.

---

extensions/teams/infra/azure.bicep
extensions/teams/infra/azure.json

* ...
- Add missing variable from Teams extension 
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

add missing variable for infra teams extension.

---

docs/design/adrs/2024-03-15-use-pytest-httpserver-as-a-mock-server-for-functional-testing.md
docs/design/adrs/README.md
docs/design/adrs/template.md

- as a mock server for functional testing
Required by https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/420

Add design document for using pytest-httpserver

---

.github/workflows/ci.yml

* Add concurrency to deploy workflow, to prevent two deployments at the same time. The concurrency is based on the name of the workflow and the branch being deployed (`main`)
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
* Can only properly test after merge

Add concurrency to deploy workflow

---

azure.yaml
code/tests/functional/README.md

* The azure app service which uses Oryx build system looks for 'requirements.txt' file. Due to poetry changes it does not find the required dependencies in pyproject.toml file. With this PR that issue will be fixed as it generates requirements.txt.
Resolves [#472](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/472)
```
[x] Yes
[ ] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
run `azd up` to deploy the application
```

azd up fix-deploying to app service

---

.coveragerc
pyproject.toml

* Now we have a `pyproject.toml` file from poetry, move the config from `.coveragerc` to this file, removing an additional file.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: chore
```
* Run tests from root of repo: `poetry run pytest -m "not azure and not functional" --cov=.`
* Coverage is the same as before

Change .coveragerc to pyproject.toml

---

code/tests/utilities/test_SecretHelper.py

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Mock SecretClient

---

docs/design/adrs/2024-03-18-use-cypres-as-a-framework-for-e2e-testing.md
docs/design/adrs/template.md

Adds an ADR for the selection of framework for UI e2e testing - Cypress. Required by #419.
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```
N/A, just verify whether the ADR makes sense based on the pros/cons.

Create ADR for using cypress as a framework for e2e testing.

---

.vscode/tasks.json

* Update path for `func: host start` task
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
* Run `func: host start` locally in VS Code

Update tasks.json for func start

---

extensions/teams/package-lock.json
extensions/teams/package.json

* We cannot upgrade to the latest version of `@types/node` as it is v20, yet this app only supports Node 16 or 18. Therefore, update the types to v18 and then close the dependabot PR.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Chore
```
* Build the code
* Run locally

Update @types/node to v18

---

code/tests/functional/backend_api/test_conversation_custom.py

Required by https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/420

Add test for failing downstream

---

.github/workflows/ci.yml

We should always destroy what we just built
```
[ ] Yes
[x] No
```
Does it destroy the environment

Always destroy

---

.devcontainer/devcontainer.json
.env.sample
code/app.py
code/backend/batch/utilities/helpers/EnvHelper.py
code/tests/functional/backend_api/conftest.py
code/tests/functional/backend_api/test_conversation_custom.py
code/tests/test_app.py
docs/LOCAL_DEPLOYMENT.md
docs/TEAMS_LOCAL_DEPLOYMENT.md
infra/app/function.bicep
infra/core/ai/cognitiveservices.bicep
infra/main.bicep
infra/main.bicepparam
infra/main.json

Closes #554, closes #197, closes #552, closes #413 
* This PR updates to the latest stable version of Azure OpenAI API version, `2024-02-01`.
* There are no changes required to the `/api/conversation/custom` endpoint, but all the changes are to the `/api/conversation/azure_byod` endpoint. This endpoint is not called by the frontend at all (and was not currently working anyway)
* Update unit tests to more closely match streamed response
* Fix issues regarding RBAC and unimplemented GET methods
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
* Update code …

Update to Azure OpenAI version 2024-02-01

---

code/app.py
code/tests/test_app.py

Closes #562 
* Adds unit tests to `app.py`, increasing coverage
* `/api/conversation/azure_byod` now returns JSON response when using data + not streaming
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Tests
```
* `poetry run pytest -m "not azure and not functional"`

Unit tests for app.py

---

.devcontainer/devcontainer.json
.vscode/settings.json

* Adds new settings so ports are automatically forwarded
* Moves some settings to `.vscode/settings.json`, as they should be applied regardless of whether a devcontainer is used or not
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Chore
```
* `az login`

Update settings, including port forwarding

---

.github/workflows/comment_coverage.yml

* Use `context` object in GitHub script rather than directly from `github` object.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
Difficult to test, as it only runs from `main`, however I have tested it in my fork.

Use `context` in 'Find associated pull request' script

---

README.md

Add meta data to the Readme so that Samples Explorer can find this repository
https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main

Add meta data for indexing

---

infra/main.bicepparam

Raising off the back of https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/discussions/431

Allow openai model to be configured via azd

---

.vscode/settings.json
azure.yaml
code/backend/batch/utilities/helpers/AzureSearchHelper.py
code/backend/batch/utilities/helpers/EnvHelper.py
code/backend/batch/utilities/tools/QuestionAnswerTool.py
code/create_app.py
code/tests/functional/backend_api/app_config.py
code/tests/functional/backend_api/tests/with_data/test_azure_byod.py
code/tests/functional/backend_api/tests/with_data/test_conversation_custom.py
code/tests/test_app.py
code/tests/utilities/test_AzureSearchHelper.py
docs/LOCAL_DEPLOYMENT.md
docs/TEAMS_LOCAL_DEPLOYMENT.md
infra/main.bicep
infra/main.json
scripts/package_frontend.ps1
scripts/package_frontend.sh

Closes #449
This PR:
* Adds support for `AZURE_SEARCH_TOP_K` and `AZURE_SEARCH_DIMENSIONS` when using custom endpoint
* Adds new env var `AZURE_SEARCH_FILTER` to both endpoints, for filtering search results
* Adds `poetry install` before deploying app
* Remove unnecessary call to OpenAI embeddings just to get `1536`
* Update tests
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
* Run code locally
* Configure the following env vars
* AZURE_SEARCH_TOP_K
* AZURE_SEARCH_FILTER
* AZURE_SEARCH_DIMENSIONS
* AZURE_SEARCH_USE_SEMANTIC_SEARCH
* …

Enable semantic search + filtering

---

docker/Frontend.Dockerfile

* Increase timeout to 230s, to match App Service
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
...

Update uwsgi HTTP timeout in Frontend.Dockerfile

---

.github/workflows/build-docker-admin.yml
.github/workflows/build-docker-backend.yml
.github/workflows/build-docker-frontend.yml

This PR replaces the custom script inside all three docker github workflows with the docker/build-push-action. This makes the github action configuration more readable and maintainable.
Required by #605.
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Other... Updates the CI/CD configuration.
```
Here's a passing build from my changes on my feature branch: https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/actions/runs/8741684840

Update Docker build workflows to use the official action

---

.github/ISSUE_TEMPLATE/subtask.md

To automatically add labels etc

Create subtask issue template

---

.github/workflows/build-with-push-docker.yml
.github/workflows/build-without-push-docker.yml
.github/workflows/tests.yml

Required for #718 
* This PR adds `merge_group` to the workflows that run on PRs, so that the workflows will run on the merge queue. This will enable us to make certain checks mandatory before merging.
* Also uses matrix strategy for running tests to reduce duplication
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: CI
```
* View workflows - 3 are running

Add `merge_group` to PRs, update workflows to use matrix strategy

---

infra/main.bicep
infra/main.json

* Fix setting the quota for embeddings
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
* Deploy code to Azure
* Check quota in deployment has updated

Fix embeddings quota

---

extensions/teams/infra/azure.bicep

Force min TLS version to 1.2

---

docs/design/adrs/2024-03-18-use-cypres-as-a-framework-for-e2e-testing.md
docs/design/adrs/2024-04-08-use-pull-throughout-for-ingestion.md
docs/design/adrs/2024-04-23-implement-prompflow-orchestration.md

Creates an ADR for deciding whether to include promptflow to this repo. 
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```
N/A

Create an ADR for deciding whether or not to add PromptFlow.

---

code/backend/batch/GetConversationResponse.py
code/backend/batch/utilities/helpers/OrchestratorHelper.py
code/backend/batch/utilities/orchestrator/LangChainAgent.py
code/backend/batch/utilities/orchestrator/OpenAIFunctions.py
code/backend/batch/utilities/orchestrator/OrchestratorBase.py
code/create_app.py
code/tests/test_GetConversationResponse.py
code/tests/test_Orchestrator.py
code/tests/test_app.py
code/tests/utilities/test_LangChainAgent.py
poetry.lock
pyproject.toml

Closes #757 
* Makes all orchestration functions async, as a precursor to Semantic Kernel
Semantic Kernel is async, therefore we need to make orchestration async.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
* Test app with orchestration strategies `openai_functions` and `langchain`
* Test Teams app extension
* Able to get response from application

Make orchestration async

---

code/backend/batch/utilities/helpers/ConfigHelper.py
code/tests/functional/backend_api/conftest.py
code/tests/functional/backend_api/tests/README.md
code/tests/functional/backend_api/tests/sk_orchestrator/conftest.py
code/tests/functional/backend_api/tests/sk_orchestrator/test_response_with_search_documents_tool.py
code/tests/functional/backend_api/tests/sk_orchestrator/test_response_with_text_processing_tool.py
code/tests/functional/backend_api/tests/sk_orchestrator/test_response_without_tool_call.py
code/tests/functional/backend_api/tests/without_data/conftest.py
code/tests/utilities/helpers/test_ConfigHelper.py

Closes #766
* Adds functional tests for semantic kernel
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Tests
```
* `pytest -m functional`
* Tests pass

Functional tests for Semantic Kernel

---

code/tests/functional/backend_api/conftest.py
code/tests/functional/backend_api/tests/with_data/test_conversation_custom.py

- In preparation for changing the tools we use to create it
- This ensures that we don't make any unintended changes to the index
Required by https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/748

Modify functional tests to include index creation

---

docs/TEAMS_EXTENSION.md
extensions/teams/env/.env.dev
extensions/teams/env/.env.test
extensions/teams/env/.env.testtool

As described in #561, the placeholder values used in `AZURE_FUNCTION_URL` need updating. The current URL value uses `<DEPLOYMENT_PREFIX>-backend`.
However, our function name now uses the formatting: https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/3705186528decdbcfc711f0e0ca3d4206d50f272/infra/main.bicep#L214
This PR updates the documentation and `.env` files to reflect this.
Fixes #561 
n/a

Update placeholder value for function URL

---

code/frontend/package-lock.json
code/frontend/package.json
poetry.lock
pyproject.toml

Related to #417 
Updated the dependencies, uploaded a document and then asked a question on it.
This will clear all the outstanding dependabot issues - but will be merged after #798

Update dependencies - 7thMay

---

.gitignore

* Adding .idea folder generated by Jetbrains IDE to gitignore
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[] Documentation content changes
```

add Jetbrains IDE generated folder to .gitignore.

---

.vscode/launch.json
code/frontend/vite.config.ts

* This PR enables debugging in macOS environments, where port 5000 is occupied by AirPlay server
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Local debug configuration
```
```
cd [repo-name]
npm install
```
* Run debug in VS Code - Frontend - in macOS
* Frontend (API) launches successfully on port 5050 and can be reached from the Frontend (UI)

fix: update local port to use 5050

---

code/backend/batch/utilities/common/SourceDocument.py
code/backend/batch/utilities/document_chunking/ChunkingStrategy.py
code/backend/batch/utilities/document_chunking/DocumentChunkingBase.py
code/backend/batch/utilities/document_chunking/FixedSizeOverlap.py
code/backend/batch/utilities/document_chunking/Layout.py
code/backend/batch/utilities/document_chunking/Page.py
code/backend/batch/utilities/document_chunking/Paragraph.py
code/backend/batch/utilities/document_chunking/Strategies.py
code/backend/batch/utilities/document_loading/Strategies.py
code/backend/batch/utilities/helpers/DocumentChunkingHelper.py
code/backend/batch/utilities/helpers/OrchestratorHelper.py
code/backend/batch/utilities/helpers/config/ConfigHelper.py
code/backend/batch/utilities/orchestrator/OrchestrationStrategy.py
code/backend/batch/utilities/orchestrator/Strategies.py
code/backend/batch/utilities/orchestrator/__init__.py
code/create_app.py
code/tests/utilities/helpers/test_ConfigHelper.py
code/tests/utilities/helpers/test_DocumentChunkingHelper.py

* Update a few occurrences where imports were [outside top level](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/import-outside-toplevel.html). 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix (`fix`)
[ ] Feature (`feat`)
[x] Code style update (formatting, local variables) (`style`)
[ ] Refactoring (no functional changes, no api changes) (`refactor`)
[ ] Documentation content changes (`docs`)
[ ] Other... Please describe: (`perf`, `test`, `build`, `ci`, `chore`, `revert`)
```
```
cd [repo-name]
npm install
```
* Run the test suite
```
poetry run pytest -m "not azure"
```
* Tests run successful and import modules as …

chore: move imports to top of files

---

.github/PULL_REQUEST_TEMPLATE.md

Fix PR template to have radio buttons in place of radio-buttons :) 

style: Fix PR template

---

code/backend/batch/utilities/orchestrator/SemanticKernel.py
code/tests/utilities/orchestrator/test_SemanticKernel.py
poetry.lock
pyproject.toml

* Update semantic-kernel to latest version
* Run code, with semantic kernel as orchestrator
* Response received, including function calls
Testing:
* Unit tests
* Functional tests
* Running locally

build: Update semantic-kernel

---

code/create_app.py
code/tests/functional/tests/backend_api/with_byod/test_conversation_flow.py
code/tests/test_app.py
infra/main.bicep
infra/main.json

* Fixes BYOD endpoint, which was not working when using data
* `azd env set CONVERSATION_FLOW byod`
* Ask question that involves data
* Response received

fix: Add `vector_fields` to Azure OpenAI On Your Data

---

.github/dependabot.yml

* Group langchain updates together, as one cannot be updated without the other

ci: Group langchain updates together

---

docker/docker-compose.yml

* use the same env_file the other two services use
```
cd [repo-name]
npm install
```
```
make docker-compose-up
```
* verify the backend can connect to the webjob storage as documented `docs/LOCAL_DEPLOYMENT.md#L114`

fix: backend .env path

---

.devcontainer/devcontainer.json

Required by https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/406

build: Add promptflow and ml tooling to dev container

---

code/backend/batch/utilities/search/search_handler_base.py
code/backend/pages/02_Explore_Data.py
code/tests/search_utilities/test_azure_search_handler.py

Fixed files visibility issue under explore data section in Admin interface where end user was not able to see more than 10 files and after this code fix we are able to see all the files.
```
cd [repo-name]
npm install
```
Upload more than 10 files from ingest data section in admin interface and verify that we are able to see all the files in explore data section. Please find below screenshots for your reference.

fix: Fixed Admin Interface: Explore Data-Files visibility issue

---

code/backend/pages/01_Ingest_Data.py

* Fixed typos for better understanding
```
cd [repo-name]
npm install
```
```
```
* ...

style: Fixed small typos

---

infra/main.bicep

* Updated the column name as "id" for the azureSearchFieldId column in bicep code
- [ x] No
```
cd [repo-name]
npm install
```
```
```
* ...

fix: Updated the column name as "id" for the azureSearchFieldId column in bicep code

---

code/backend/pages/03_Delete_Data.py

* ...
- [X ] No
*  Steps to reproduce: 
Navigate to Chat with your data Admin URL
Click on 'Delete Data' tab
Select files to Delete
Scroll down and select multiple checkboxes to delete
```
cd [repo-name]
npm install
```

fix: Added changes in Delete Data file

---

code/backend/pages/03_Delete_Data.py

Original issue raised: [Admin Site Broke : Traceback - in _checkbox checkbox_proto.label = label · Issue #372 · Azure-Samples/chat-with-your-data-solution-accelerator (github.com)](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/372)
Steps to reproduce: 
Navigate to Chat with your data Admin URL
Click on 'Delete Data' tab
Select files to Delete
Scroll down and select multiple checkboxes to delete
Expected result: Files are selected for delete and Delete button is visible.
Actual result: Page refreshed automatically, Delete button not visible till the page refreshes and selected files are deselected.
Please find the attachment.
I am able to delete data and it is not refreshing after selecting files
​
* ...
- [X ] No
```
git clone …
```

fix: Delete section moved as form section to avoid refreshing on clicking check box

---

code/backend/batch/utilities/helpers/config/config_helper.py
code/backend/pages/04_Configuration.py
code/tests/utilities/helpers/test_config_helper.py

Original issue raised: 
[Error while setting advanced image processing on ['jpeg', 'jpg', 'png', 'tiff', 'bmp'] · Issue #1250 · Azure-Samples/chat-with-your-data-solution-accelerator (github.com)](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/1250)
Describe the bug
While the documentation (https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/advanced_image_processing.md ) states that Advanced image processing can be done for ['jpeg', 'jpg', 'png', 'tiff', 'bmp'] , however configuring in the admin app the advanced image processing i do get the following errors:
Traceback (most recent call last): File "/tmp/8dcb7fb38d2a08c/pages/04_Configuration.py", line 404, in ConfigHelper.save_config_as_active(current_config) File …

fix: exception should come in correct way to user on configuration page and corrected the message

---

poetry.lock
pyproject.toml

To fix the issue:
```
Traceback (most recent call last):
File "app.py", line 22, in <module>
from create_app import create_app # noqa: E402
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/app/create_app.py", line 17, in <module>
from backend.batch.utilities.helpers.orchestrator_helper import Orchestrator
File "/usr/src/app/backend/batch/utilities/helpers/orchestrator_helper.py", line 5, in <module>
from ..orchestrator.strategies import get_orchestrator
File "/usr/src/app/backend/batch/utilities/orchestrator/strategies.py", line 2, in <module>
from .open_ai_functions import OpenAIFunctionsOrchestrator
File "/usr/src/app/backend/batch/utilities/orchestrator/open_ai_functions.py", line 5, in <module>
from .orchestrator_base import OrchestratorBase
File …
```

fix: Downgrade semantic kernel

---

code/backend/batch/utilities/orchestrator/open_ai_functions.py

* To address the error related to the answer variable
```
cd [repo-name]
npm install
```
After implementing this fix, you should no longer encounter the error below while using the Chat App. You can review the logs in the application log stream.
**ERROR: create_app: Exception in /api/conversation cannot access local variable ' answer' where it is not associated with a value
UnboundLoca1Error: cannot access local variable 'answer' where it is not associated with a value**
Please find below screenshot for your reference:

fix: Error handling for 'answer' variable

---

code/backend/batch/utilities/helpers/env_helper.py
code/create_app.py
code/tests/functional/tests/backend_api/with_byod/test_conversation_flow.py
code/tests/test_app.py

Fix for BYOD without data issue
- [x ] No
```
cd [repo-name]
npm install
```
Select BYOD flow and before upload documents and try to chat.
* ...

fix: Fix for byod without data issue

---

code/backend/batch/utilities/helpers/env_helper.py

This update ensures backward compatibility by using existing environment variables (AZURE_OPENAI_MODEL, AZURE_OPENAI_MODEL_NAME, AZURE_OPENAI_EMBEDDING_MODEL) if the new consolidated environment variables (AZURE_OPENAI_MODEL_INFO, AZURE_OPENAI_EMBEDDING_MODEL_INFO) are not available. This change allows already deployed solutions to continue functioning without modification.
- [x ] No
```
cd [repo-name]
npm install
```
Verify that already deployed solutions to continue functioning without modification.

fix: Retain compatibility with existing deployments by using previous environment variables if new ones are unavailable

---

code/backend/pages/01_Ingest_Data.py

*  This fix will allow users to upload the files with filenames in Hebrew language in ingest document screen (Admin app)
```
cd [repo-name]
npm install
```
**Before Fix:**
**After Fix:**
*  Try to upload the file with the filename in Hebrew language and verify if the file upload is successful.

fix: Addressed the file upload issue with filenames in Hebrew language in ingest documents screen

---

code/backend/pages/04_Configuration.py

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

fix: fixed config save issue

---

.github/workflows/ci.yml
Makefile

* Fix provided for CI workflow where resource group is creating automatically from the GitHub variables.
CI workflow - Automated

fix: ci workflow fix for Bicep deployment

---

.github/CODEOWNERS.txt

* Added the code owners file to make sure we are aware of the changes which are getting merged to the repo.

ci: Added required code owners for CWYD

---

.github/CODEOWNERS

Update CODEOWNERS with additional owner (Francia Riesco)

ci: Update CODEOWNERS with additional owner

---

infra/app/function.bicep
infra/app/web.bicep
infra/core/database/cosmos-sql-role-assign.bicep
infra/core/host/functions.bicep
infra/core/storage/storage-account.bicep
infra/main.bicep
infra/main.bicepparam
infra/main.json

* This PR contains the fixes for SFI - Storage and Cosmos DB
```
cd [repo-name]
npm install
```
```
```
* ...

fix: SFI Fixes & scope reverted to subscription

---

.github/workflows/ci.yml
Makefile
infra/main.bicep
infra/main.json

* Auth type set default to RBAC
* Reverted Resource group scope from make file and yml files
```
cd [repo-name]
npm install
```
```
```
* ...

fix: Auth type set default to rbac and removed resource group from bicep

---

.github/workflows/build-docker-images.yml
.github/workflows/build-docker.yml

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

fix: Workflow issue fix on docker image

---

code/backend/batch/utilities/helpers/env_helper.py

fix: import error in env_helper.py

fix: import error in env_helper.py

---

infra/main.bicep
infra/main.json

*  The purpose of updating the hosting model using an ARM template is to configure and deploy the application specifically in a container environment for improved scalability and management.
- Ensure no other values exist for the hosting model in both ARM/Bicep templates.
- Deploy the templates and confirm that only "container" is allowed.
- Verify the output or resource state reflects the "container" hosting model.

fix: Update Hosting Model Configuration in ARM/Bicep Template

---

infra/main.json

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

fix: Update main.json for changes conversation flow changes in bicep

---

code/backend/batch/utilities/parser/output_parser_tool.py

* For fixing the duplicate citation reference number and citation contains ']' brackets
```
cd [repo-name]
npm install
```
```
```
* ...

fix: Response getting ']' brackets, it's inconsistent

---

.github/workflows/build-docker.yml

[Implement Consistent Versioning and Tagging for Accelerator Images]
[User Story 12494](https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/12494): [POC]Ensure Consistent Image Versioning Across CWYD Accelerator

feat: Implement Consistent Versioning and Tagging for Accelerator Images

---

docs/best_practices.md

Updated numerical queries section in best practices readme
```
cd [repo-name]
npm install
```
```
```
* ...

docs: updated numerical queries section in best practices readme

---

code/backend/pages/04_Configuration.py

* Improvements to admin Document processing configuration validation logic:
*  Added a `should_save` flag to control whether the configuration should be saved based on validation results.
*  Enhanced validation checks to ensure t fields are not left blank in the document processing configuration.
*  Added a conditional check to save the configuration only if all validations pass.
```
cd [repo-name]
npm install
```
```
```
* ...

fix: Admin configuration issue fix

---

.github/workflows/stale-bot.yml

* Identify & List Stale Merged Branches with No Activity in Last 3 Months
* Identify & List PR Approved & Merged Branches (Older Than 30 Days)
* List Open PR Branches With No Activity in Last 3 Months
```
cd [repo-name]
npm install
```
```
```
* ...

fix: Update stale-bot.yml

---

.github/CODEOWNERS

This pull request updates the `.github/CODEOWNERS` file to include additional owners for the repository.
* [`.github/CODEOWNERS`](diffhunk://#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7L5-R5): Added `@Vinay-Microsoft` and `@aniaroramsft` to the list of default owners for the repository.
```
cd [repo-name]
npm install
```
```
```
* ...

docs: added new owner name

---

infra/main.bicep
infra/main.json

- This PR introduces the following changes to main.bicep for seamless environment setup via azd up:
1. Added a new output variable: DATABASE_TYPE
2. Renamed existing outputs to match expected env variable names used in the application
3. Ensures that .env is generated with the correct variables during deployment
4. This will help in running the application locally and facilitate easier debugging
```
cd [repo-name]
npm install
```
Verify that the following are valid:
1. Run azd up and ensure the .env file correctly includes the new DATABASE_TYPE output.
2. Verify that the renamed output variables are accurately reflected and consumed by the application.
3. Confirm that the application is reading values correctly from the …

fix: Enhance Bicep Outputs for Environment Variable Configuration in .env File

---

tests/e2e-test/pages/webUserPage.py
tests/e2e-test/tests/test_poc_chat_with_your_data.py

This pull request enhances the end-to-end tests for the web user interface by adding functionality to interact with citation links in chatbot responses. Key changes include new locators for citation elements, methods for interacting with citations, and updates to existing test workflows to validate citation behavior.
* Added new locators for citation-related elements: `TOGGLE_CITATIONS_LIST`, `CITATIONS_CONTAINER`, and `CITATION_BLOCK` in `webUserPage.py`. These locators enable interaction with citation links in chatbot responses.
* Introduced methods in `webUserPage.py` for managing citations:
- [`click_reference_link_in_response`](diffhunk://#diff-793bafc03ad1881188556c0964d2db689b25e311524eefd640c20543616fd2afR83-R126): Opens the citation link in the latest chatbot response.
- …

test: add citation link interaction support to e2e tests

---

.github/workflows/broken-links-checker.yml

This pull request updates the GitHub Actions workflow for the broken links checker to improve maintainability and clarity. The changes include replacing custom scripts with reusable actions and enhancing the workflow's readability.
* Replaced the custom script for identifying changed Markdown files in pull requests with the `tj-actions/changed-files` action, simplifying the process and reducing custom code.
* Updated the step for checking broken links in changed files to use the output from the `changed-files` action, improving accuracy and consistency.
* Renamed and clarified step names to better describe their purpose, e.g., distinguishing between PR-specific and manual trigger workflows.
```
cd [repo-name]
npm install …
```

ci: Updated workflow for checking broken links in Markdown files

---

.github/workflows/ci.yml
.github/workflows/test-automation.yml
Makefile
scripts/disable_auth.sh
tests/e2e-test/pages/webUserPage.py
tests/e2e-test/tests/test_chat_with_your_data.py

This pull request introduces significant updates to the GitHub Actions workflows and the `Makefile` to enhance deployment automation, improve error handling, and streamline test execution. Key changes include the addition of deployment outputs and URL extraction, updates to the `deploy` job, and the refactoring of test automation to accept dynamic inputs.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR11): Added `workflow_dispatch` to trigger the workflow manually. Updated the `deploy` job to include outputs for deployment URLs (`web_url` and `admin_url`) and a `DEPLOYMENT_SUCCESS` flag. Enhanced the deployment process with URL extraction and logging, and added a final status check for deployment success. …

ci: refactor deployment workflow to include dynamic URL outputs, e2e test orchestration, and improved Makefile targets

---

infra/main.bicep
infra/main.json

* Introduces conditional logic to support/fix multiple hosting models (`code` and `docker`) in the `AzureWebJobsStorage` output configuration. The changes ensure that the correct storage value is selected based on the hosting model.
```
cd [repo-name]
npm install
```
```
```
* ...

fix: Oneclick deployment issue fix

---

infra/app/function.bicep
infra/main.json

* PR will fix the docker deployment fix for the function app issue.
```
cd [repo-name]
npm install
```
```
```
* ...

fix: onclick deployment issue fix
