- .devcontainer/devcontainer.json
This adds the ability to run this solution in a vscode Dev Container. It will install python 3, azure cli, Functions Core Tools and bicep automatically once opening
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
- Install "Remote Development" extension in vscode.
- Clone repo in WSL
- Open in vscode and follow prompt to "Open in Development Container"
- Profit!
Verify that the following are valid by running them in your dev container terminal.
func --version
bicep --version
az --version
python --version
This is the first PR. I will add the other developer build steps if you think this is a benefit. Related to #69
> Add DevContainer

- .devcontainer/devcontainer.json
- extensions/backend/requirements.txt
- Install python dependencies after creation
- This avoids the need for developers to install them manually
- Aligned the version of streamlit between the base app and extensions to avoid a conflict
- Install all recommended VSCode extensions
- This avoids the need for developers to install them manually
- Set default function path
- This avoids a popup requesting this on startup
- Set python interpreter path
- This enabled VSCode to automatically detect installed dependencies
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
Open the project …
```
> Various dev container improvements

- docker/AdminWebApp.Dockerfile
- Set it to the root of the code dir `/usr/local/src`
- This fixes an issue where you get a MissingModule error after a restart of the application
Fixes https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/87
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
1. Rebuild admin image and deploy new version
2. Navigate to a non-homepage page
3. Restart the application
4. Restart the page
```
> Set PYTHONPATH env var in admin app

- docker/AdminWebApp.Dockerfile
- docker/Backend.Dockerfile
- docker/WebApp.Dockerfile
- align on the latest python 3.11 version
- there is no 3.12 version for `mcr.microsoft.com/azure-functions/python`
- bump to bookworm arch in admin image
- remove `python-tk` installation as it's no longer present, nor does it seem to be required
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
> Update docker images to use same python version

- .github/dependabot.yml
* Increase the number of pip dependabot PRs that can be open at once to 50
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: CI/CD/dependencies update
```
Run dependabot after merge
Dependabot logs show that it is able to open a PR for each dependency that needs updating.
Closes #146
> Increase dependabot pip open pull requests

- code/app/app.py
- infra/deployment.bicep
- infra/deployment.json
PR #212 changed the default from `rbac` to `keys` - however these values should also be changed too
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
This change should default to keys until we resolve the versioning of "latest" containers
> Setting all defaults to `keys`

- code/app/frontend/src/components/Answer/Answer.tsx
- code/app/frontend/src/pages/chat/Chat.tsx
- It was being added to the whole page everytime an answer was returned
- This meant that if **any** content on the page was copied the alert was being shown multiple times based on how many answers there had been
- This change will mean the alert will now only be shown when an answer is copied and only once
Required by https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/215
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
* Test …
> Fix duplicate copy warning alert

- code/app/requirements.txt
- code/requirements.txt
- code/utilities/tools/ContentSafetyChecker.py
- extensions/backend/requirements.txt
- tests/test_DocumentChunking.py
* Updates to latest version of most dependencies
* Dependabot has raised multiple PRs for these but combined into a single PR to save time testing each individually
* Tested locally and packaged as a Docker image deployed to Azure both in keys and rbac mode
* Leaves out openai for now due to large changes being required
* Leaves out azure-search-documents for now as latest version is not compatible with langchain
* Discussion: https://github.com/langchain-ai/langchain/discussions/13245
* PR to fix: https://github.com/langchain-ai/langchain/pull/15659
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Documentation content …
```
> Update to latest version of most dependencies

- code/app/requirements.txt
- code/requirements.txt
- extensions/backend/requirements.txt
Reduce dependabot surface by removing unneeded references
Removed 
- matplotlib
- plotly
- scikit-learn
Upgraded
- tiktoken
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
Run tests
> Remove plotting libraries and upgrade tiktoken

- .github/dependabot.yml
- .github/workflows/ci.yml
Current build is triggered during Pull Request. When this occurs on a forked branch, the user will not have access to the secrets and the deployment will fail
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
CI only runs on push to main for the moment.
> Only deploy the accelerator on a push to main

- code/backend/batch/utilities/helpers/ConfigHelper.py
- infra/main.bicep
- infra/main.json
The Orchestration Strategy is set in the bicep when the infrastructure is created. That value is set in the App Settings of the Web Apps. However, it was not being set as an output of the bicep. This means when you debug things locally, it is using the default of "openai_function" even if you set it as langchain.
Also when you set up a default configuration from the Admin page, then it was hardcoded to be openai_function. This change will use whatever was configured at initial setup.
You can still change this value and save the settings. It stores this in the `config` container in Azure Storage
Fixes #56
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
[ ] Refactoring (no functional …
```
> Orchestration Strategy

- code/backend/batch/requirements.txt
I believe that the latest round of dependabot changes did not change all of the instances of some of the packages which has meant that the Oryx build in the WebApp never finishes the pip install phase.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
Deploy to the AdminWeb succesfully
Before: (never completes)
After:
> Align requirements so there are no conflicts

- code/backend/batch/requirements.txt
Another missing requirements update that was missed with dependabot updates: fake-useragent.
This one causes the devcontainer to not build, but is not needed in the adminweb
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
Does the postCreate.sh work in the devcontainer.
> Requirement alignment (fake-useragent)

- README.md
- These resources are now created when running `azd up`
- This change was made in https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/113 but this section of the README was missed
> Remove openai pre-req from readme

- code/app.py
- code/tests/test_app.py
* This pull request improves the json.dumps calls by avoiding the need to manually replace newline characters, and setting ensure_ascii=False. Required by https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/45
```
[ ] Yes
[ x] No
```
```
[x ] Bugfix
[ ] Feature
```
*  I added unit tests that cover the flows I've edited, so just running the unit test build should suffice.
```
python -m pytest code/tests/test_app.py
```
Verify that the tests pass.
> Improve jsonlines dump to avoid ensuring ascii characters.

- .github/workflows/comment_coverage.yml
- .github/workflows/tests.yml
- code/.coveragerc
Required for #408 
This PR adds commenting to PRs with code coverage.
The commenting is done using a third-party GitHub action, [pytest-coverage-comment](https://github.com/marketplace/actions/pytest-coverage-comment). It is pinned to a specific Git SHA to prevent automatically picking up new changes to the repo which could potentially be malicious.
The commenting is handled in a separate workflow, as the token in the `Tests` workflow only has read-only permissions and cannot comment on PRs when running from forks. The separate workflow for commenting only has write permissions to pull requests, and no other permissions.
This commenting action does not have the ability to fail a run based on a threshold, therefore this will be introduced in a separate PR. The next PR will also handle …
> Add coverage to PRs

- code/app.py
- code/backend/batch/utilities/helpers/EnvHelper.py
- code/dev-requirements.txt
- code/tests/functional/backend_api/app_config.py
- code/tests/functional/backend_api/conftest.py
- code/tests/functional/backend_api/test_config.py
- code/tests/test_app.py
- code/tests/utilities/test_EnvHelper.py
- Based on the ADR https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/design/adrs/2024-03-15-use-pytest-httpserver-as-a-mock-server-for-functional-testing.md
- Added `OPENAI_API_BASE` to config endpoint for ease of testing
- Allowed `OPENAI_API_BASE` to be set via an env var
- Previously this was only generated based on resource name but we
need more control to set the mock server url
- Add unit tests to `EnvHelper` for this new functionality
Requried by https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/420
> Introduce functional test mock server

- .devcontainer/devcontainer.json
- .github/workflows/comment_coverage.yml
- .github/workflows/tests.yml
- .gitignore
Closes #408 
This PR fails the build if the coverage is lower than the current coverage in the main branch. It does this by downloading the coverage artifact from the latest build of `main`, and extracting the coverage from the XML report. It then feeds this into the pytest command with the `--cov-fail-under` flag. If the coverage cannot be obtained from the main branch, it should default to 0.
The coverage from main is rounded down to the nearest integer, as the coverage obtained from main is usually to 2dp (e.g. 33.95%), while the coverage from pytest is to a much higher precision (33.948339483%), meaning that even if there were no changes to Python code, 33.948339483% < 33.95% would fail the build.
Also, this PR allows the coverage to be commented on the PR even if tests fail, and …
> Fail build if coverage is too low

- .github/workflows/comment_coverage.yml
* Due to a bug in the action, `report-only-changed-files` does not work for PRs from forks, therefore disable this for now until fixed. Note that the action still works and posts successfully, however the workflow exits with an error.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
* Tested in fork
> Disable report-only-changed-files for forks

- .github/workflows/comment_coverage.yml
* We have hit secondary rate limits from the `issuesAndPullRequests()` endpoint, therefore change to use the `pulls.list()` endpoint instead.
* Add retries to the API call
* Only use the GitHub API to get the pull request number if it isn't already available on the `github` object
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: CI
```
*  Difficult to test as it only runs on main. I have tested in my own fork. I will review that it is working after merging.
> Change logic to find associated pull request

- code/tests/functional/backend_api/app_config.py
- code/tests/functional/backend_api/conftest.py
- code/tests/functional/backend_api/request_matching.py
- code/tests/functional/backend_api/test_conversation_custom.py
- To ensure we are making the correct calls, with the correct api keys, api version, index information and request bodies
- Implemented using a generic request matcher for now
- This should be added to the mock server library by https://github.com/csernazs/pytest-httpserver/issues/293
- Added extra tests rather then combining al the verifications in one test
- This is so that the failure reason should be clearer
- I was concerned that this would significantly increase the test run time however it made no difference and some runs after were actually quicker then if it was a single test
Required by https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/420
> Verify the downstream calls being made by /conversations/custom

- Makefile
- infra/main.bicep
- infra/main.json
* Fix CI, by setting `AZURE_APP_SERVICE_HOSTING_MODEL` to `code` before deploying.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
* Test after merge
> Set AZURE_APP_SERVICE_HOSTING_MODEL for CI

- code/frontend/package-lock.json
- code/frontend/package.json
Upgrades dependency libraries for the frontend UI. 
```
[ ] Yes
[x ] No
```
Dependency upgrades for the frontend UI. 
Deploy, open the frontend UI and check whether chat is working correctly. I ingested a file and ensured the answer is relevant and is from the file.
> Update frontend dependencies - fluentui/react, types/node, types/react, types/react-dom, 

- code/app.py
- poetry.lock
- pyproject.toml
* This PR adds `httpx` instrumentation, so that calls to Azure OpenAI appear in Application Insights
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
* Deploy
* Make request to `/api/conversation/custom`
* View Application Insights
> Add httpx instrumentation

- code/backend/batch/utilities/common/SourceDocument.py
- code/tests/common/test_SourceDocument.py
When checking for Blob Storage we should only check that the domain ends with blob storage domain rather than it just contains it based on Code Security CWE-20
Tested by Unit Tests
> CWE-20 - Code Security

- code/backend/batch/AddURLEmbeddings.py
- code/backend/batch/BatchPushResults.py
- code/backend/batch/BatchStartProcessing.py
- code/backend/batch/GetConversationResponse.py
- code/backend/batch/utilities/helpers/DocumentProcessorHelper.py
- code/backend/batch/utilities/helpers/EnvHelper.py
- code/backend/batch/utilities/orchestrator/LangChainAgent.py
- code/backend/batch/utilities/orchestrator/OpenAIFunctions.py
- code/backend/batch/utilities/parser/OutputParserTool.py
- code/create_app.py
- code/tests/functional/backend_api/app_config.py
- code/tests/functional/backend_api/common.py
- code/tests/functional/backend_api/tests/with_data/conftest.py
- code/tests/functional/backend_api/tests/without_data/conftest.py
- code/tests/utilities/test_EnvHelper.py
Required by https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/637
> Add additional logs and stop using root logger

- infra/main.bicep
- infra/main.json
Stop B3 being downsized to B1
Wait a day!
> Stop B3 being downsized to B1

- code/backend/batch/utilities/orchestrator/LangChainAgent.py
- code/tests/utilities/test_LangChainAgent.py
- This is to address a security issue where stacktraces may get returned
to the user https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/security/code-scanning/7
- This exception will be caught in the
`create_app.conversation_custom()` function https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/b291c55eeded213a70508db57b4d9318d53a3115/code/create_app.py#L371
> Allow langchain agent errors to propogate

- extensions/teams/package.json
- This is to fix a security issue around it's transitive dependency, semver https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/security/dependabot/36
- This older version of nodemon is currently pinning semver to an older version with security vulnerbilities
- This was recently downgraded by https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/599 to align with the teams toolkit recommendations, however this is not a critical dependency and is only used to monitor code changes during local development
> Bump version of nodemon

- extensions/teams/package-lock.json
- extensions/teams/package.json
- The previous PR (https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/678) did not update the `package-lock.json` so the issue is not resolved.
- This was due to the `@types.node` version being invalid. I've changed it to the latest `18.*` version as listed here https://www.npmjs.com/package/@types/node?activeTab=versions
> Correctly bump node versions

- code/backend/batch/utilities/helpers/EnvHelper.py
- code/tests/functional/backend_api/common.py
- code/tests/functional/backend_api/tests/with_data/conftest.py
- code/tests/functional/backend_api/tests/without_data/conftest.py
- code/tests/utilities/test_EnvHelper.py
- The current setup means we create 23 instances of this when submitting a question via the UI
- A timed single question via the UI took 62 seconds to get an answer
- After this change, the same question took 8 seconds to get an answer
- Obviously this isn't very robust testing! But the improvement is obvious
- Decided to pick this up as it's having an affect on code design reviews
Required by https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/508
> Make EnvHelper a singleton

- code/backend/batch/utilities/helpers/EnvHelper.py
- We're occasionally seeing the below error when ingesting:
```
Exception while executing function: Functions.batch_push_results Result: Failure
Exception: AttributeError: 'EnvHelper' object has no attribute 'AZURE_BLOB_ACCOUNT_NAME'
Stack:   File "/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/dispatcher.py", line 505, in _handle__invocation_request
call_result = await self._loop.run_in_executor(
has context menu
```
- I believe this is caused by multiple threads running at the same time
- The first one creates the instance and starts populating the config
- The second sees the instance the first one has created, but tries to use it before the config has been populated
- This change wraps the code in a lock to ensure only one thread at a time can get an …
> Resolve muiltithreading issues around EnvHelper singleton

- .github/workflows/tests.yml
* Only attempt to download the coverage when running on a PR
There have been some errors when attempting to run the workflow on branches, rather than pull requests, as `github.base_ref` is only available when running on a PR.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: CI
```
* Check workflow run for this PR
> Fetch coverage only for PRs

- code/backend/batch/utilities/helpers/EnvHelper.py
- code/tests/functional/backend_api/app_config.py
- code/tests/functional/backend_api/tests/without_data/conftest.py
- Tests were failing locally for me due to a clash with azd env vars
- Change to set ALL env vars used
- This stops any predefined env vars from setting things we don't want
in functional tests e.g. Key Vault
- Also ensure previous env vars are restored after tests
> Fix issue with env vars clashing with functional tests

- .github/workflows/build-docker-admin.yml
- .github/workflows/build-docker-backend.yml
- .github/workflows/build-docker-frontend.yml
This PR corrects the tags in the docker github workflows so that they are pushed to the right registry. Required by #605 
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Other... Fixes the CI/CD config
```
The passing build on my feature branch, including the push step is here: https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/actions/runs/8751927224/job/24018560508
(Compare with failing https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/actions/runs/8750849851/job/24015217486 which was trying to push to Docker hub instead)
> Fix the tag to include the registry name on the docker github aworkflows.

- .github/workflows/build-docker.yml
Changing the build-without-push github action to only run the docker login step if we need to push. 
Rationale: We don't need to do this if we aren't pushing, plus forcing docker login on every PR breaks the builds for forks which don't have the docker password secret. 
```
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[ ] Feature
[ x] Other... CI/CD config update
```
Verify the docker builds on this PR.
> Make docker login conditional on push for docker github actions.

- .github/workflows/bicep-audit.yml
Adds bicep audits to the GitHub workflows and uploads results to github security.
This pull request introduces a new GitHub Actions workflow that validates bicep templates. The workflow is triggered on push and pull request events to the `main` branch, specifically for changes to `.bicep` files. It runs on the latest Ubuntu environment and uses the `microsoft/security-devops-action@preview` action to analyze the templates. If the repository owner is 'Azure-Samples', it uploads the analysis results to the Security tab using the `github/codeql-action/upload-sarif@v3` action.
* [`.github/workflows/bicep-audit.yml`](diffhunk://#diff-dcd02a3340d2c1100a6c1d18a9ce9201fd1f7c78692a1d91467248fb73787bbaR1-R35): Added a new GitHub Actions workflow that validates bicep templates on push and pull …
> Create bicep-audit workflow

- .flake8
- .gitattributes
- Makefile
A user has reported that they are getting CRLF on a bash file. I do not see this on mine, but in order to fix #742 we can enforce line endings from git.
Whilst there I noticed that `make lint` was throwing errors so I have excluded the `.venv` directory as this is a generated folder. I have also removed the extra `build-frontend` that was being called in `ci`
> Enforced LF line endings

- infra/main.bicep
- infra/main.bicepparam
- infra/main.json
Closes #790 
* Updates default OpenAI deployment to `gpt-35-turbo-16k`, which supports more tokens for the bigger prompt.
```
[ ] Yes
[x] No (The model version is the same, but more tokens are supported)
```
```
[ ] Bugfix
[x] Feature
```
* Deploy solution
* Add docs to knowledge base
* Ask question from knowledge base
* Response received
> Update default model to `gpt-35-turbo-16k`

- infra/app/web.bicep
- infra/main.json
Closes #643
* Adds missing `Storage Blob Data Contributor` role to the web app
This used to fail silently when attempting to fetch the config fron Storage, falling back to the default config , but following #706 it now fails with an error.
Change was originally included in #787, but moving to separate PR as #787 may stay open for a long time.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
* Deploy RBAC solution
* Ask question
* Response received
> Add missing storage permission

- .github/dependabot.yml
Since we'll soon be adopting conventional commit messages, this change updates the Dependabot commit-message to prefix it with "build" so that it will meet the conventional commit format. The effect of this change on Dependabot PR naming will be for example,
Before:
> Bump openai from 1.24.0 to 1.26.0 
After:
> build: Bump openai from 1.24.0 to 1.26.0 
I have based this change on [this blog post](https://dev.to/aloisseckar/keeping-dependencies-in-your-github-projects-up-to-date-with-dependabot-16bg), which has [this example dependabot.yml](https://github.com/AloisSeckar/demos-nuxt/blob/main/.github/dependabot.yml) which produces [these pull requests](https://github.com/AloisSeckar/demos-nuxt/pulls). I will need to verify the formatting …
> Add prefix to dependabot commit message

- docs/LOCAL_DEPLOYMENT.md
Update the documentation to correct the `az deployment` command which was outdated.
> docs: Update docs if deploying through az

- infra/main.bicep
- infra/main.json
Fix the broken CI. According to the logs, we have this error. I believe it is because we define it as a bool, but we only allow "false" as a value.
```
/workspaces/chat-with-your-data-solution-accelerator/infra/main.bicepparam(29,47) : Error BCP033: Expected a value of type "false" but the provided value is of type "bool".
```
I am however unsure why this passed the previous build!
> build: Boolean only accepting a false is causing bicep ERROR in CI

- .github/workflows/pr-title-checker.yml
Currently the PR title checker is not mandatory, so this PR adds the `merge_group` workflow trigger to include it as a mandatory check.
However, as described [here](https://github.com/amannn/action-semantic-pull-request/issues/236), the Action only runs when triggered by `pull_request_target` or `pull_request` events. 
The solution is to have it included in the merge_group event, but not triggered by it, as described [in this comment](https://github.com/amannn/action-semantic-pull-request/issues/236#issuecomment-1695654373).
Resolves #859 
> ci: Adds merge group event to PR title checker

- code/backend/batch/utilities/common/SourceDocument.py
- code/backend/batch/utilities/helpers/AzureSearchHelper.py
- code/backend/batch/utilities/helpers/LLMHelper.py
- code/backend/batch/utilities/helpers/embedders/PushEmbedder.py
- code/backend/batch/utilities/search/AzureSearchHandler.py
- code/backend/batch/utilities/search/IntegratedVectorizationSearchHandler.py
- code/backend/batch/utilities/search/Search.py
- code/backend/batch/utilities/search/SearchHandlerBase.py
- code/backend/batch/utilities/tools/QuestionAnswerTool.py
- code/tests/common/test_SourceDocument.py
- code/tests/functional/backend_api/conftest.py
- code/tests/functional/backend_api/tests/default/test_conversation_custom.py
- code/tests/functional/backend_api/tests/sk_orchestrator/test_response_with_search_documents_tool.py
- code/tests/functional/backend_api/tests/sk_orchestrator/test_response_without_tool_call.py
- code/tests/search_utilities/test_AzureSearchHandler.py
- code/tests/search_utilities/test_IntegratedVectorizationSearchHandler.py
- code/tests/search_utilities/test_Search.py
- code/tests/utilities/helpers/processors/test_IntegratedVectorizationEmbedder.py
- code/tests/utilities/helpers/test_AzureSearchHelper.py
- code/tests/utilities/helpers/test_LLMHelper.py
- code/tests/utilities/helpers/test_PushEmbedder.py
- code/tests/utilities/test_QuestionAnswerTool.py
- This is preparation for adding an additional image vector field for
advanced image processing
- I've tried to keep changes to a minimum
- Still using langchain in the question and answer tool for now
- Increased unit test coverage
Required by https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/748
> refactor: Remove langchain from index operations

- infra/main.bicep
- infra/main.bicepparam
- infra/main.json
Relates to #796 
This is a part fix for #796 as we need to design this so that it works for people who use azd, plain bicep and the "Deploy to Azure" button. Not all environment variables have a corresponding input bicep param as they are outputs of the bicep. I'm also unsure how brittle we will make this if we allow people change the name of Azure resources through the environment variables, I think it was better if they were bicepparam's and the ENV values were the output. I will look into this next.
This PR just adds those values that are ENV and params so that you can deploy using `azd up` and then update using `azd env set KEY VALUE` and then `azd up` again and have the deployment respect the value you have just set.
This also has a small tweak to the B3 -> B1 issue
> build: Adding params that we have ENV for

- README.md
- docs/best_practices.md
- docs/customer_truth.md
Reduce the words in the main README.md so that we can focus on the intent of the accelerator
- small change to pull best practices and solution truth into their own pages.
There is no change to the existing text in these new pages.
> docs: Best Practices in its own page

- infra/app/adminweb.bicep
- infra/app/function.bicep
- infra/app/storekeys.bicep
- infra/app/web.bicep
- infra/app/workbook.bicep
- infra/core/ai/cognitiveservices.bicep
- infra/core/host/appservice.bicep
- infra/core/host/functions.bicep
- infra/core/security/keyvault-access.bicep
- infra/core/security/keyvault.bicep
- infra/core/security/registry-access.bicep
- infra/core/storage/storage-account.bicep
- infra/main.bicep
- scripts/generate_arm_templates.sh
* Fixes the `generate_arm_templates.sh` script, which was failing silently
* Format all Bicep files
There are no actual changes to the infra.
> fix: Fix generate_arm_templates.sh script, reformat all Bicep files

- .devcontainer/devcontainer.json
- code/app.py
- code/backend/Admin.py
- code/create_app.py
- code/tests/test_app.py
Wanted to investigate the benefit of using pylint which seems to give us better vscode integration.
This PR is more for discussion as it relates #864
> style: Investigate pylint for PEP8

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
There was a problem with the Functions Core Tools that the compression was not working.  This meant that we had to tag the version we used.
By not defining that we have to run on Bullseye and use Bookworm (debian 12) instead, we no longer need to pin that version. Testing that this works on Windows first and then seeing if we can get Mac to work on top of this.
Relates to #866 
Please bear in mind that you will need to "rebuild" your devcontainer
After:
```sh
❯ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
❯ azd version
azd version 1.9.2 (commit …
```
> build: Bullseye -> bookworm

- code/create_app.py
Fixes #930
This was accidentally changed in a previous linting test and needs reverting. This worked locally, but is obviously throwing errors in App Service. This change reverts the code back to yesterdays version.
> fix: Revert linting bug

- .github/workflows/tests.yml
- Makefile
Closes #935 
* Runs Python unit and functional tests together, so we get an overall coverage from both tests
* View tests from this PR
> ci: Run Python unit and functional tests together

- code/backend/batch/utilities/helpers/env_helper.py
* fix the relative import instead of absolute inside env_helper
* Resolves: #650 
* This PR retro fixes the comment at https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/905#discussion_r1610059674
> fix: Use relative path for ConversationFlow import so that shared code works in all applications

- code/backend/batch/utilities/search/search_handler_base.py
- code/backend/pages/03_Delete_Data.py
- code/tests/search_utilities/test_azure_search_handler.py
- code/tests/search_utilities/test_integrated_vectorization_search_handler.py
* Resolves #975 
* Deleting from index every time user deletes from Admin site
* Deleting url or documents from Admin website deletes it from storage as well as index
* Deleting document directly from Blob Storage deletes the documents from index
> fix: delete url embeddings from index when deleting from Admin website

- code/frontend/src/components/Answer/Answer.tsx
Web app - Part listed as reference is not included in Citation preview panel and after fixing this bug part no will give proper citation preview panel on the right side of screen.
* If you type something in chatbot for eg. "Describe in more detail the risks from market volatility" we are getting response with the citation listed as Parts 19 and 14, respectively. This "Part" of the citation is not included in the Citation preview panel.
* After receiving response in chatbot click on reference link which contains part no, that part no should include in the Citation preview panel.
> fix: PSL-BUG-1850-Fixed

- .vscode/settings.json
- code/backend/batch/utilities/helpers/env_helper.py
- code/backend/batch/utilities/tools/question_answer_tool.py
- code/tests/functional/app_config.py
- code/tests/utilities/tools/test_question_answer_tool.py
- docs/advanced_image_processing.md
- infra/main.bicep
- infra/main.bicepparam
- infra/main.json
Required for #750
* Set a limit to the number of images that are passed to the LLM when using advanced image processing. Defaults to 1
* Deploy code, with advanced image processing enabled
* Upload similar images
* Make query about images
* Check number of images passed to LLM
> feat: Set limit for advanced image processing images

- .github/workflows/create-release.yml
When the release action runs, it checks out `main` which is what the release is created from. 
In some cases, this could mean that whilst the `CI` is completing new merges to `main` could get checked in.
This update specifies the ref to use when doing the checkout, so that the ref of the branch that triggered the workflow is used.
Therefore the release is generated from the ref that completed the CI run.
> fix: create release using ref of triggering workflow

- code/frontend/src/pages/chat/Chat.module.css
Text is overlapping in the citation section.
1-Type something on chat bot for e.g. "Provide the details of European Equities Fund" 
2-Click on references and select "Woodgrove Asset Mana...Management Funds.pdf - Part 81".
3-Find the text overlapping in citation section.
In citation section , you will see there is no overlapping text now.
> fix: Text is overlapping in the citation section (Line spacing) 

- infra/main.bicep
- infra/main.json
* Fix the conditional output that breaks deployment when orchestration strategy is not `prompt_flow`
* Deploy
> fix: Fix Machine Learning output on deployment

- README.md
- infra/prompt-flow/create-prompt-flow.sh
Relates to #406 
If you run `azd auth login` from your devcontainer, you may not have ran `az login` which means that during the Post Provision hook, the `pfazure` command can fail
Dont login to Azure using `az login`
run `azd up` with PromptFlow enabled
> fix: Login to Azure in post provision step if not already

- code/frontend/src/components/QuestionInput/QuestionInput.module.css
- code/frontend/src/pages/chat/Chat.module.css
- code/frontend/src/pages/chat/Chat.tsx
- code/frontend/src/pages/layout/Layout.module.css
- code/frontend/src/pages/layout/Layout.tsx
1. **Images**
Need to add an alternative text for images and icons.
2. **High contrast modes**
By providing borders to the fields.
3. **Resizing: Text in the page should be adaptable to resizing up to 200% zoom in 1280p without overlap.** 
Resize of the content without overlap based on the above resolution.
1. **Images**:
Open CWYD URL.
Open inspect
Alternative text for Images and icons.
2. **High contrast modes**
Open CWYD URL.
Go to system setting ->Accessibility->Contrast themes->select aquatic in drop down-> apply.
Go to CWYD URL, you can find the screen, does not have border, so that it's difficult for user text direction and where to ask the question.
3. **Resizing: Text in the page should be adaptable to resizing up to 200% zoom in 1280p without overlap.** 
Open CWYD URL.
Go to …
> fix: Added UI changes (Landing Screen)

- code/backend/Admin.py
- code/backend/pages/common.css
**1. High contrast modes** 
Open CWYD Admin URL.
Go to system setting ->Accessibility->Contrast themes->select aquatic in drop down-> apply.
Go to CWYD Admin URL, you can find the screen, does not have separation border between left collapse and main screen.
Expected result: By providing borders to the fields.
**2. Resizing: Text in the page should be adaptable to resizing up to 200% zoom in 1280p without overlap.** 
Open CWYD Admin URL.
Go to system setting ->System->Display resolution->select 1280P in drop down-> apply.
Go to CWYD Admin URL, you can find the screen, the content is not adaptable.
Expected result: Resize of the content so that the adaptable in the above resolution.
**1. High contrast modes** 
Open CWYD Admin URL.
Go to system setting ->Accessibility->Contrast …
> fix: [Bug-4714-Admin] Borders for contrast mode and fixed resizing issue for 1280p

- infra/core/ai/cognitiveservices.bicep
- infra/main.bicep
- infra/main.bicepparam
- infra/main.json
- This was causing the deployment to fail when advanced image processing
was enabled as it overrides the default location in the `main.bicep`
to `""`
> fix: Correctly set computer vision location

- code/backend/Admin.py
- code/backend/batch/utilities/helpers/env_helper.py
- code/backend/pages/01_Ingest_Data.py
- code/backend/pages/02_Explore_Data.py
- code/backend/pages/03_Delete_Data.py
- code/backend/pages/04_Configuration.py
- code/tests/functional/tests/functions/advanced_image_processing/test_advanced_image_processing.py
- code/tests/utilities/helpers/test_llm_helper.py
- code/tests/utilities/tools/test_question_answer_tool.py
It's currently failing with:
```
code/backend/Admin.py:34:1: E302 expected 2 blank lines, found 1
code/backend/Admin.py:39:1: E305 expected 2 blank lines after class or function definition, found 1
code/backend/pages/01_Ingest_Data.py:23:1: E302 expected 2 blank lines, found 1
code/backend/pages/01_Ingest_Data.py:28:1: E305 expected 2 blank lines after class or function definition, found 1
code/backend/pages/01_Ingest_Data.py:30:1: E302 expected 2 blank lines, found 1
code/backend/pages/02_Explore_Data.py:30:1: E302 expected 2 blank lines, found 1
code/backend/pages/02_Explore_Data.py:35:1: E305 expected 2 blank lines after class or function definition, found 1
code/backend/pages/03_Delete_Data.py:21:1: E302 expected 2 blank lines, found 1
code/backend/pages/03_Delete_Data.py:26:1: E305 …
```
> style: Reformat code to fix build

- code/frontend/src/components/Answer/Answer.module.css
- code/frontend/src/pages/chat/Chat.module.css
- code/frontend/src/pages/layout/Layout.module.css
Revert the font size changes and removed extra padding
```
cd [repo-name]
npm install
```
open cwyd chatbot page and check the font size and spacing
> fix: font size changes reverted and removed extra padding

- code/backend/batch/utilities/integrated_vectorization/azure_search_indexer.py
- code/backend/batch/utilities/integrated_vectorization/azure_search_skillset.py
- code/tests/functional/conftest.py
- code/tests/functional/tests/functions/integrated_vectorization/test_integrated_vectorization_resource_creation.py
- code/tests/utilities/integrated_vectorization/test_azure_search_indexer.py
- code/tests/utilities/integrated_vectorization/test_azure_search_skillset.py
* This PR adds the OCR skill when using Integrated Vectorization to enable search on images.
* Relates to #973 
```
cd [repo-name]
npm install
```
* When Integrated Vectorization is enabled, user should be able to upload images with text and search those images
> feat: Integrated Vectorization - adding OCR skill

- extensions/teams/cards/cardBuilder.ts
- extensions/teams/teamsBot.ts
The CELA disclaimer for AI generated content that is present in the web app is missing from the Teams version
Go to teams app and ask any question and check whether we are getting disclaimer text along with response.
Please refer the below screenshot:
> fix: Add AI disclaimer to Teams extension

- .github/workflows/comment_coverage.yml
* The bug that prevented `report-only-changed-files` working on forks has now been fixed, therefore setting the value to `true`
> ci: Enable `report-only-changed-files` in `comment_coverage.yml`

- extensions/teams/cards/cardBuilder.ts
* fixes #1104 
```
cd [repo-name]
npm install
```
```
publish the teams bot
```
* can open a document storage url that contains spaces in the filename
> fix: teams bot double encode issue

- code/tests/utilities/helpers/test_azure_computer_vision_client.py
The **test_raises_exception_if_bad_response_code** test in **code/tests/utilities/helpers/test_azure_computer_vision_client.py** fails intermittently. The use of **time.sleep(0.3)** in the previous test, **test_vectorize_image_calls_computer_vision_timeout**, is causing the issue. Therefore, we have updated the test case to remove **time.sleep**, ensuring that all tests now pass consistently.
- [x ] No
```
cd [repo-name]
npm install
```
Verify **Tests** job (Run Python Tests)
> fix: Remove time.sleep from test case

- code/backend/pages/04_Configuration.py
Assisant type section title under Configuration on admin page not visible when collapsed
* ...
Added tittle as "Assistent type configuration"
Jump over configuration section and try to expand and collapse the "Assistant Type" section 
Expected result: Title "Assistant type configuration " should be visible when collapsed.
> fix: Added title as "Assistant type configuration"

- code/frontend/src/components/QuestionInput/QuestionInput.module.css
- code/frontend/src/components/QuestionInput/QuestionInput.tsx
- code/frontend/src/pages/chat/Chat.tsx
mic recording and send button functionality not in sync
Overlapping of "Listening.." and "Stop Generating" messages
After recording query when we send the it,  "Listening.." and "Stop Generating" are overlapping 
once clicked on send button 
microphone recording should be stopped 
Overlapping of "Listening.." and "Stop Generating" messages
After recording query when we send the it,  "Listening.." and "Stop Generating" are overlapping 
```
cd [repo-name]
npm install
```
1. click on mic to start the recording 
2. once we click on send button the recorded sentence is sent, but mice don't stop recording
3. if user keeps talking boat concatenate the first said sentence and currently speaking statement and combinedly provides the result.
> fix: Disable send button until speech recording stopped

- infra/main.bicepparam
Added azureOpenAISystemMessage and azureSearchTopK param in main.bicepparam file to set the value of AZURE_SEARCH_TOP_K and AZURE_OPENAI_SYSTEM_MESSAGE env variable in azure using azd env set and azd up command
```
cd [repo-name]
npm install
```
Run below commands from VS code powershell terminal:
azd env set AZURE_SEARCH_TOP_K 15 
azd up
azd env refresh
And check whether value of AZURE_SEARCH_TOP_K is getting updated in azure and local both. And the value should not get reset to 5 in .env file in your local.
Please find below screenshot for your reference:
> fix: AZURE_SEARCH_TOP_K and AZURE_OPENAI_SYSTEM_MESSAGE keeps reseting after running azd env set and azd up command

- infra/main.bicep
- infra/main.json
Added azureOpenAISystemMessage and azureSearchTopK param in main.bicep files for function app to set/update the value of AZURE_SEARCH_TOP_K and AZURE_OPENAI_SYSTEM_MESSAGE env variable in azure function app using azd env set and azd up command
```
cd [repo-name]
npm install
```
**Run below commands from VS code powershell terminal:**
azd env refresh
azd set AZURE_OPENAI_SYSTEM_MESSAGE "You help people find all the information."
azd up
**SSH to the function app:**
echo $AZURE_OPENAI_SYSTEM_MESSAGE
Check whether you are able to see the expected SYSTEM_MESSAGE.
Please find below screenshot for your reference:
> fix: Added missing env variables in main.bicep for function app

- code/backend/pages/common.css
Bug: https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/5571
There should not be shift of arrow during collapsible scenario of drop down and there should be gap between the fields.
Steps to reproduce: 
Navigate to Chat with your data URL
Click on 'Ingest Data' tab
Click on first drop down
Observe the arrow, there is slight shift in towards left and right 
For the second drop down the input fields edge is slightly overlapped to another fields.
This happens during 1920X1080 Screen resolution with browser 100%.
```
cd [repo-name]
npm install
```
There should not be shift of arrow during collapsible scenario of drop down and there should be gap between the fields.
**Note**:  For desktop resolution 1920 * 1080, display scale …
> fix:  Ingest data - UI issue overlapping components

- code/backend/batch/utilities/helpers/config/default.json
Bug:  5527 
it is for uploading JPEG file and in explore dropdown jpeg history also should be visible
Deploy CWYD 
On Admin page under ingest data upload .PNG file
Under Explore data section's "Explore data' dropdown check if that uploaded file is visible or not 
.PNG is visible when I checked.
Then upload .JPEG file and check under "Explore data" dropdown, if it's visible or not
for me it is not visible 
Image
Repeat step number 5 for .MD files
Image  
getting same result, not visible 
Image
cd [repo-name]
npm install
```
> fix: Type JPG upload issue fix on explore page under admin

- code/frontend/src/components/Answer/Answer.module.css
Bug: https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/6028/?view=edit
Content is out of box/region
- User should have ingested data using admin URL 
- User should have CWYD web URL 
- Ingest the file attached in attachment section 
- Ask the question summarize github-recovery-codes
**The resolution is** 
Scale: 150%
Display_Resolution: 1920 x 1080 
Browser: 100% zoom
```
cd [repo-name]
npm install
```
> fix: Content is out of box/region

- code/backend/pages/04_Configuration.py
- code/backend/pages/common.css
Configuration tab "Reset configuration to Defaults" confuses the user whether it is button or dropdown. and adding x button for close the popup
cd [repo-name]
npm install
1. go to the Admin page, Scroll down under "Configuration" section
2. Click on "Reset to default configuration" tab 
3. the up arrow indicates the tab as dropdown, but it pops up this window. 
4. It creates confusion whether it is dropdown or button.
> fix: Configuration tab "Reset configuration to Defaults" confuses the user whether it is button or dropdown.

- infra/main.json
* Updated the column name as "id" for the azureSearchFieldId column in main.json file
```
cd [repo-name]
npm install
```
Check whether the value of AZURE_SEARCH_FIELDS_ID variable got updated to "id" in search index after doing the deployment. Please find below screenshot for your reference:
> fix: Updated the column name as "id" for the azureSearchFieldId column in main.json file

- code/backend/pages/04_Configuration.py
* To handle the refresh in configuration page
```
cd [repo-name]
npm install
```
```
```
* Configuration page refresh on continuous selecting check boxes. Fixed the refresh issue. Attached screen shot for reference below :
> fix: Admin config page refresh issue fix

- .flake8
- code/backend/batch/utilities/helpers/embedders/push_embedder.py
- code/backend/batch/utilities/helpers/env_helper.py
- code/tests/utilities/helpers/test_push_embedder.py
* Allows large PDFs to be ingested.
* Fixes #1267 
*  Follow steps document in Local Deployment
* Ingest a large file.  My tested one had ~850 pages and was 18.5 Megs in size.
* All chunks should be in search index (can take a while)
* Modified existing upload test to pass with 1 batch.
* Added another test to check for multiple batches.
* Also had to do some code cleanup per black and flake8, though they conflicted in some rules so added exceptions in flake config file.
> feat: Upload to AI Search in Batches

- azure.yaml
- scripts/package_frontend.ps1
- scripts/package_frontend.sh
Azure App Service now supports poetry directly so this is no longer needed
> refactor: Stop generating requirements.txt during deployment

- code/backend/pages/01_Ingest_Data.py
* Enable the users to upload files with multilingual filenames in the Admin App for improved accessibility
```
cd [repo-name]
npm install
```
**Before Fix:**
**After Fix:**
* Upload files with filenames in English, Italian, French, German, etc., and verify whether the files are uploading successfully.
> feat: Implemented functionality to enable multilingual filename uploads in the Admin App.

- docker/Admin.Dockerfile
- docker/Frontend.Dockerfile
Fixes #1464 
Use new docker syntax for ENV in Dockerfiles `ENV key=value`
We cannot exclude the append behaviour of PYTHONPATH for the moment as there is no ignore-rule
See [https://github.com/docker/buildx/issues/2751](https://github.com/docker/buildx/issues/2751)
In our case PYTHONPATH is actually blank in both cases - but it is legitimate pattern to append to the PYTHONPATH in case the base image adds at a later date.
CI will build without any warnings
> fix: Use new docker syntax for ENV

- .github/dependabot.yml
- .github/workflows/build-docker-images.yml
- .github/workflows/build-docker.yml
- .github/workflows/ci.yml
- .github/workflows/sync-branches.yml
- .github/workflows/tests.yml
- code/create_app.py
- infra/app/function.bicep
- infra/app/web.bicep
- infra/core/database/cosmos-sql-role-assign.bicep
- infra/core/host/functions.bicep
- infra/core/storage/storage-account.bicep
- infra/main.bicep
- infra/main.bicepparam
- infra/main.json
* This PR contains the Workflow update, SFI Fixes
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: Merging Dev changes to Main

- code/frontend/src/pages/chat/Chat.tsx
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: Commit changes bug

- infra/main.bicep
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: add conversation flow in environment variable for adminweb app

- code/backend/batch/batch_push_results.py
- code/backend/batch/utilities/helpers/azure_form_recognizer_helper.py
- code/backend/batch/utilities/helpers/config/config_helper.py
- code/backend/batch/utilities/helpers/embedders/integrated_vectorization_embedder.py
- code/backend/batch/utilities/helpers/embedders/postgres_embedder.py
- code/backend/batch/utilities/helpers/embedders/push_embedder.py
- code/backend/batch/utilities/helpers/env_helper.py
- code/backend/batch/utilities/helpers/llm_helper.py
- code/backend/batch/utilities/orchestrator/lang_chain_agent.py
- code/backend/batch/utilities/orchestrator/open_ai_functions.py
- code/backend/batch/utilities/orchestrator/prompt_flow.py
- code/backend/batch/utilities/orchestrator/semantic_kernel.py
- code/backend/batch/utilities/parser/output_parser_tool.py
- code/backend/batch/utilities/search/azure_search_handler.py
- code/backend/batch/utilities/search/integrated_vectorization_search_handler.py
- code/backend/batch/utilities/tools/content_safety_checker.py
- code/backend/batch/utilities/tools/question_answer_tool.py
- code/backend/pages/01_Ingest_Data.py
- code/backend/pages/02_Explore_Data.py
- code/backend/pages/04_Configuration.py
- code/create_app.py
Add missing logs
- [ X] No
```
cd [repo-name]
npm install
```
Verify the logs
> fix: Add Missing Logs

- scripts/parse_env.ps1
- scripts/parse_env.sh
Fix Duplication of Flattened JSON Keys in .env File During Multiple Script Runs
> fix: Fix Duplication of Flattened JSON Keys in .env File During Multiple Runs

- code/frontend/src/pages/chat/ChatHistoryListItem.tsx
Fixed issue with duplicate warning messages in chat history update
[Bug 9545](https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/9545): [QA] - CWYD - Warning message displayed twice in chat history update
```
cd [repo-name]
npm install
```
Deploy CWYD with GPT 4o
Go to CWYD Admin and enable chat history if not enabled
Go to CWYD web url and save chat history conversations
Click on Show chat history button and click on Edit icon for a chat thread
Disconnect from network
Update the text in chat thread title and click on Tick icon
Observe the warning message
The warning message "Error: could not rename file" should be displayed only once.
> fix: Warning message displayed twice in chat history update

- .github/workflows/build-docker-images.yml
- .github/workflows/ci.yml
- .github/workflows/create-release.yml
- .github/workflows/pr-title-checker.yml
- .github/workflows/stale-bot.yml
- .github/workflows/tests.yml
This pull request includes several updates to the GitHub Actions workflows to improve clarity and functionality. The changes involve renaming workflows for better readability, adjusting cron schedules, and adding a new event trigger.
Workflow renaming for clarity:
* [`.github/workflows/build-docker-images.yml`](diffhunk://#diff-2817fc9ec6443e19233164eefa86576a0972ce81bcf0ec4a04f96d6119db038eL1-R1): Renamed to "Build Docker and Optional Push" for better description of functionality.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL1-R1): Renamed to "Validate Deployment" to better reflect the purpose of the workflow.
* [`.github/workflows/create-release.yml`](diffhunk://#diff-8ac33fe295df086d3e55df1eb01194819d34cc0f5f54076dba96c …
> chore: Updated workflow names and trigger schedule

- .github/workflows/ci.yml
- scripts/checkquota.sh
* ...
This pull request introduces a quota check mechanism to the CI pipeline and updates the related scripts and workflow files. The most important changes include adding a script to check Azure quotas, modifying the CI workflow to run this script, and handling quota check failures.
Quota check implementation:
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR32-R77): Added steps to run the quota check script, send notifications on quota failure, and fail the pipeline if the quota check fails.
* [`scripts/checkquota.sh`](diffhunk://#diff-da95ac25ccacdf794788c8cabac6042f20be6e3dec4772e955e0d81b5ce7582fR1-R97): Added a new script to check Azure quotas for specific regions and models, ensuring that the required capacities are …
> ci: implement quota check in CI Pipeline to ensure resource availability in supported region

- scripts/checkquota.sh
* ...
This pull request includes a small change to the `scripts/checkquota.sh` file. The change updates the delimiter used to split the `AZURE_REGIONS` string from a space to a comma and space.
Change in delimiter for `AZURE_REGIONS`:
* [`scripts/checkquota.sh`](diffhunk://#diff-da95ac25ccacdf794788c8cabac6042f20be6e3dec4772e955e0d81b5ce7582fL4-R4): Updated the delimiter from a space to a comma and space for reading `AZURE_REGIONS`.
No
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: comma separated values

- code/backend/pages/04_Configuration.py
This pull request includes a minor update to the `reset_config_dialog` function in `code/backend/pages/04_Configuration.py`. The change modifies the text of a button to improve clarity.
* Updated the button label from `":red[Reset Now]"` to `":red[Reset]"` to simplify the wording in the `reset_config_dialog` function.
> fix: Changed the button label from "Reset Now" to "Reset"

- .github/dependabot.yml
- .github/workflows/scheduled-Dependabot-PRs-Auto-Merge.yml
* Introduced a scheduled GitHub Actions workflow to auto-approve and auto-merge Dependabot PRs targeting the dependabotchanges branch.
* Also optimized the dependabot.yml configuration to group dependency updates by ecosystem and path, significantly reducing PR noise.
```
cd [repo-name]
npm install
```
```
```
* ...
> chore: dependabot poc changes

- .github/workflows/scheduled-Dependabot-PRs-Auto-Merge.yml
* Enhanced rebase logic to handle merge conflicts using --strategy-option=theirs.
* Implemented multi-strategy auto-merge (merge, squash, rebase) with fallback handling.
* Improved overall script reliability and compatibility with repo-level merge restrictions.
```
cd [repo-name]
npm install
```
```
```
* ...
> chore: updated auto merge workflow

- infra/main.bicep
- infra/main.json
This pull request makes several updates to the `infra/main.bicep` file, primarily standardizing the naming conventions for various Azure resources by replacing dynamic string concatenations with explicit parameter definitions. This improves readability and ensures consistency in resource names.
* Updated the naming convention for the App Service plan to use `asp-${resourceToken}` instead of concatenating abbreviations (`[infra/main.bicepL15-R15](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L15-R15)`).
* Standardized the naming of database and web-related resources, such as Cosmos DB (`cosmos-${resourceToken}`), PostgreSQL (`psql-${resourceToken}`), and Web App (`app-${resourceToken}`), replacing dynamic abbreviations with explicit parameter assignments …
> fix: hardcoded abbreviations in bicep

- code/backend/pages/01_Ingest_Data.py
* ...
This pull request introduces several improvements and updates across various files and components, focusing on infrastructure naming conventions, frontend enhancements, backend functionality, and configuration management. The most important changes include the addition of a `.dockerignore` file, updates to environment variables, enhancements to frontend components, backend validation improvements, and the introduction of standardized abbreviations for resource naming.
* Added `infra/abbreviations.json` to define standardized abbreviations for Azure resource naming conventions, ensuring consistency across infrastructure.
* Updated `infra/main.bicep` to use abbreviations for naming Azure resources, such as `psql-` for PostgreSQL and `oai-` for OpenAI services. (Fb0606efL10R10, …
> fix: error in 'Process and Ingest Web Pages' under 'Add URLs to the Knowledge Base' (CWYD)

- .github/workflows/broken-links-checker.yml
This pull request adds a new GitHub Actions workflow to automatically check for broken links in Markdown files. The workflow supports two triggers: pull requests and manual runs.
New workflow addition:
* [`.github/workflows/broken-links-checker.yml`](diffhunk://#diff-67e26d77769066e1f1b5633a89f931c691eabfd57782a0767fa13ebb15319af4R1-R48): Created a workflow named "Broken Link Checker" that runs on pull requests to check for broken links in added or modified Markdown files, and supports manual execution to check all Markdown files in the repository. It uses the `lychee-action` for link validation and includes configurations for verbose output, excluding email links, and ignoring certain URL patterns.
> feat: Add Broken Link Checker workflow for Markdown files

- docs/prompt_flow.md
- infra/main.bicep
- infra/main.json
- scripts/checkquota.sh
- scripts/quota_check_params.sh
* This pull request introduces changes to standardize the SKU naming convention for OpenAI models by replacing `Standard` with `GlobalStandard` across infrastructure configuration and scripts. It ensures consistency in model definitions and quota checks. Below is a breakdown of the most important changes:
* Updated the SKU name from `'Standard'` to `'GlobalStandard'` in the `defaultOpenAiDeployments` definition in `infra/main.bicep`.
* Modified the SKU name in `infra/main.json` to reflect the change from `'Standard'` to `'GlobalStandard'` and updated the `templateHash` value accordingly. [[1]](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L8-R8) [[2]](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L931-R931)
* Updated …
> chore: OpenAI models by replacing `Standard` with `GlobalStandard` across infrastructure in the Bicep

- code/create_app.py
- code/frontend/src/components/Answer/Answer.test.tsx
- code/frontend/src/components/Answer/Answer.tsx
- code/tests/functional/tests/backend_api/default/test_speech_token.py
- code/tests/test_app.py
The purpose of this pull request is to enhance the security of the **Speech Synthesis** integration by eliminating the exposure of the **Azure Speech API key** in browser network calls.
Previously, the frontend received and used the Speech API subscription key directly to initialize the speech synthesizer, which could be viewed in browser developer tools. While access to the app is restricted via Entra ID, exposing sensitive keys in client-side code is still a security risk.
To resolve this, we have:
- Replaced the use of the long-lived Speech API key with a short-lived authorization token retrieved securely from the backend.
- Updated both backend and frontend code to support token-based initialization of the Azure Speech Synthesizer.
This change ensures sensitive credentials are no …
> fix: Remove Exposed Speech Service API Key from Network Calls

- infra/core/security/role.bicep
- infra/main.bicep
- infra/main.json
- tests/e2e-test/tests/test_chat_with_your_data.py
This pull request introduces improvements to the role assignment module in the infrastructure code, making principal type detection more flexible and simplifying usage in main deployment scripts. It also includes minor cleanups in the end-to-end test scripts for better readability.
**Infrastructure improvements:**
* Updated `core/security/role.bicep` to allow automatic principal type detection by making `principalType` optional and including it only if explicitly provided. This enables more flexible role assignments for different principal types.
* Commented out explicit `principalType: 'User'` assignments in the main infrastructure deployment (`infra/main.bicep`), so principal type is now auto-detected unless specifically set. This reduces redundancy and potential errors. …
> refactor: make principal type optional in role assignments and clean up e2e tests

- extensions/teams/config.ts
- extensions/teams/index.ts
- extensions/teams/infra/azure.bicep
- extensions/teams/infra/azure.parameters.json
- extensions/teams/infra/botRegistration/azurebot.bicep
- extensions/teams/package.json
- extensions/teams/scripts/enable-service-principal.js
- extensions/teams/teamsapp.yml
- extensions/teams/tsconfig.json
Cosmos&Postgres]- Error during Team integration
```
cd [repo-name]
npm install
```
> fix: Cosmos&Postgres]- Error during Team integration

- code/backend/pages/01_Ingest_Data.py
On clicking the 'Process and Ingest Web Pages' button, if the URL is valid, then clear the text area.
> feat: On click of button teatarea should be clear

- .github/workflows/ci.yml
This pull request makes a minor update to the resource group creation step in the GitHub Actions workflow. The change adds a `CreatedBy="Pipeline"` tag when creating a new Azure resource group, which helps with resource tracking and auditing.
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: Add 'CreatedBy' tag when creating resource group

- README.md
- azure.yaml
- docs/LOCAL_DEPLOYMENT.md
- docs/NON_DEVCONTAINER_SETUP.md
This pull request updates the documentation and configuration to require Azure Developer CLI (azd) version 1.18.0 or higher for deploying the solution accelerator. It clarifies this version requirement in multiple documentation files and enforces it in the project configuration. Additionally, there are minor formatting improvements.
**Azure Developer CLI (azd) version requirement:**
* Added a `requiredVersions` section to `azure.yaml` to enforce that `azd` version 1.18.0 or higher is required for deployment.
* Updated `docs/LOCAL_DEPLOYMENT.md` and `docs/NON_DEVCONTAINER_SETUP.md` to clearly state and highlight the azd version requirement, including download links and version notes. [[1]](diffhunk://#diff-c79519d2609bc70c20c082a1fdbf47dfca79e43ec4342b8b9dba87f46be94096R7-R8) …
> docs: Updated README, azure.yml for minimum azd version 1.18.0
